name: Build Examples
on: [push]
jobs:
  build-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
         go-version: '1.19'
      - name: Install Tinygo
        run: |
          echo "Install TinyGo 0.26.0..."
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.26.0/tinygo_0.26.0_amd64.deb
          echo "dd7d47bc15be3690932394faca93ac6433a309cbe2957fc71e5688e567cd6d1ce0b8bf1e92455058e4547db6a70e176af85fe1b507537966a160bf88a819a101 tinygo_0.26.0_amd64.deb" | sha512sum --check
          sudo dpkg -i tinygo_0.26.0_amd64.deb
      - name: build examples
        run: |
          for i in _examples/*; do
            echo ${GITHUB_WORKSPACE}/$i
            cd ${GITHUB_WORKSPACE}/$i && tinygo build -target=wasi
          done
