name: Compute TinyGo SDK Test
on: [push]
jobs:
  sdktest-go-latest:
    runs-on: ubuntu-latest
    concurrency: 
      group: SdkTestJob
      cancel-in-progress: true
    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap-integration-test
      - name: Check our bootstrap dependencies were installed correctly, and in our $PATH
        run: |
          fastly version
          viceroy --version
          tinygo version
      - name: Install Go
        uses: actions/setup-go@v2
        with:
         go-version: '1.18' 
      - name: compute-sdk-go Integration Tests Job
        uses: ./.github/actions/compute-sdk-test
        id: sdktest
        with:
          config: './_integration_tests/sdk-test-config.json'
  sdktest-go-previous:
    runs-on: ubuntu-latest
    needs: [sdktest-go-latest]
    concurrency: 
      group: SdkTestJob
      cancel-in-progress: true
    steps:
      - name: Checkout fastly/compute-sdk-go
        uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap-integration-test
      - name: Check our bootstrap dependencies were installed correctly, and in our $PATH
        run: |
          fastly version
          viceroy --version
          tinygo version
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' 
      - name: compute-sdk-go Integration Tests Job
        uses: ./.github/actions/compute-sdk-test
        id: sdktest
        with:
          config: './_integration_tests/sdk-test-config.json'
