name: Validate
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: golint (revive)
        run: |
          go install github.com/mgechev/revive@v1.0.9
          test -z "$(revive ./... | tee /dev/stderr)"
      - name: go vet
        run: go vet ./...
      - name: staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@2022.1.1
          staticcheck ./...
      - name: gofumpt
        run: |
          go install mvdan.cc/gofumpt@v0.1.1
          test -z "$(gofumpt -s -l -d -e . | tee /dev/stderr)"
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: go test
        run: go test -race ./...
