name: Validate
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: go vet
        run: go vet ./...
      - name: staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
      - name: nilness
        run: |
          go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@latest
          nilness ./...
      - name: ineffassign
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          ineffassign ./...
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: go test
        run: go test -race ./...
